# Generated by Django 5.0.2 on 2024-03-26 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile_no', models.CharField(max_length=15, null=True)),
                ('customer_email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20)),
                ('awb_number', models.CharField(max_length=20)),
                ('return_code', models.IntegerField()),
                ('return_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(max_length=20)),
                ('shipment_status', models.CharField(max_length=100)),
                ('shipment_status_datetime', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('hub_location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=10)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('customer_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.customerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('new_ticket_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_no', models.CharField(max_length=50)),
                ('problem_category', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('date_of_purchase', models.DateField()),
                ('invoice_copy', models.TextField(blank=True, null=True)),
                ('video_of_issue', models.TextField(blank=True, null=True)),
                ('front_image', models.TextField(blank=True, null=True)),
                ('back_image', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Open', 'Open')], default='Open', max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='ticket_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.pickuprequest'),
        ),
    ]
