# Generated by Django 5.0.2 on 2024-04-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_no', models.CharField(max_length=50)),
                ('problem_category', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('date_of_purchase', models.DateField()),
                ('invoice_copy', models.TextField(blank=True, null=True)),
                ('video_of_issue', models.TextField(blank=True, null=True)),
                ('front_image', models.TextField(blank=True, null=True)),
                ('back_image', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile_no', models.CharField(max_length=15, null=True)),
                ('customer_email_id', models.EmailField(max_length=254)),
                ('house_no', models.CharField(max_length=10)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
