# Generated by Django 5.0.2 on 2024-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_imagefields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagefields',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='front',
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='invoice_copy',
            field=models.ImageField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='video_of_issue',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
