# Generated by Django 5.0.2 on 2024-05-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_delete_imagefields_remove_pickuprequest_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
