"""
Django settings for smartwearable project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%vxi%vw2_w@rb)m-*7f$u!-$=yx6myk#j1iy(%d47)t%qj0!dm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Installed apps
    'ticketapp',
    'user_module',
    'rest_framework',
    'logistics',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_module.middleware.AutoLogoutMiddleware',
    'csp.middleware.CSPMiddleware',
    'user_module.middleware.LoginAttemptMiddleware',
]

ROOT_URLCONF = 'smartwearable.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartwearable.wsgi.application'

MAX_LOGIN_ATTEMPTS = 3
LOGIN_ATTEMPT_COOLDOWN = 1800 #30 mins

SESSION_COOKIE_SECURE= True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SECURE_HSTS_SECONDS = 7776000  # 90 days
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
PERMISSSIONS_POLICY = {
    'geolocation': "'self'",
    'midi': "'self'",
    'camera': "'self'",
}
CSP_DEFAULT_SRC = ["'self'",
                   "https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js",
                   "http://stageusermanagementapi.xbees.in/api/auth/generateToken",
                   "http://api.staging.shipmentmanifestation.xbees.in/shipmentmanifestation/reverse",
                   "http://api.staging.shipmenttracking.xbees.in/GetReverseShipmentAuditLog",
                   "https://titan-ecomm-exp-app-uat.us-e2.cloudhub.io/api/exp/case/v1/UpdateCaseStatus",
                   "https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js",
                   "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css",
                   "https://code.jquery.com/jquery-3.3.1.slim.min.js",
                   "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js",
                   "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js",
                   "https://cdn.jsdelivr.net/npm/sweetalert2@11",
                   "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css",
                   "https://fonts.googleapis.com/",
                   "'unsafe-inline'",
                   "https://fonts.gstatic.com/",
                   "https://fonts.googleapis.com/",
                   "'unsafe-eval'",
                   "data:",
                   "https://cdn.jsdelivr.net/jquery/latest/jquery.min.js",
                   "https://cdn.jsdelivr.net/momentjs/latest/moment.min.js",
                   "https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js",
                   "https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"
                ]
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smartwearable',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'index'

LOGOUT_REDIRECT_URL = 'login'

LOGIN_URL = 'login'